### ISSUE TITLE
fixed cameras on COS

### ISSUE THREAD

**Issue by ckrsls** [maximeraafat/BlenderNeRF#11]
Hi, thanks for this great add-on.
I wonder if I could set fixed mutiple cameras to render a dynamic scene using the Camera on Sphere method?

**Comment by maximeraafat** [comment]
Hi @ckrsls, I am not exactly sure about what you are trying to achieve, but the **Camera on Sphere** method is not well suited for being used with prefixed cameras. The **COS** method will render `Frames` amount of training frames sampled from the `BlenderNeRF Sphere`, where the camera position will change randomly according to the timeframe.

However, the scene will dynamically change alongside the **BlenderNeRF** capturing process. More precisely, if you have an animated scene key-framed from frame 1 to 100, and you run one of the methods (**SOF**, **TTC** or **COS**) for the same amount of frames, the rendered frames will capture the changes in your scene.

In your specific case, you might want to consider manually fixing a few cameras (say **N** cameras), and run for instance the **TTC** method for each camera separately on **T** frames. This will give you a set of **N** datasets (one per camera), each containing one `transforms_train.json` file with **T** frames. The frames will have captured the dynamic scene.

Hope this answers your question :)
