### ISSUE TITLE
DroNeRF: new paper on determining ideal capture (render) locations:

### ISSUE THREAD

**Issue by avclubvids** [maximeraafat/BlenderNeRF#15]
This might be valuable for determining where each camera should be to assure maximum quality and coverage:

https://arxiv.org/pdf/2303.04322.pdf

**Comment by maximeraafat** [comment]
Hi @avclubvids,

Thanks for your suggestion, interesting finding! I'll definitely consider adding it to my _to read_ list.
Feel also free to fork **BlenderNeRF** to extend it to your needs :)
