### ISSUE TITLE
How to get the donut dataset?

### ISSUE THREAD

**Issue by YiChenCityU** [maximeraafat/BlenderNeRF#2]
Hi, This is a good project about nerf. However could you explain more about how to get the dataset used in colab? Thanks very much.

**Comment by maximeraafat** [comment]
Hi, the donut was obtained by following Andrew Price's famous [Blender 3.0 Beginner Donut Tutorial](https://youtube.com/playlist?list=PLjEaoINr3zgFX8ZsChQVQsuDSjEqdWMAD). I then simply animated a camera in a circle around the donut for 100 frames, and played _Subset of Frames_ on half of them (i.e., with a frame step = 2). I hope this answers your question!

If you want the same exact results as in the README , I can share the .blend file here
