### ISSUE TITLE
Request for Feature Addition: Simultaneous Rendering of Depth Maps with Optical Images and JSON Integration

### ISSUE THREAD

**Issue by TaoF02** [maximeraafat/BlenderNeRF#22]
Hello～

I hope this message finds you well. I am writing to express my sincere appreciation for your remarkable work. Your project has been instrumental in my work, and I have found it incredibly helpful.

Given the immense value your project has already provided, I would like to kindly request the addition of a new feature. It would be immensely beneficial if you could incorporate the functionality to 【 render depth maps simultaneously with optical images and integrate them into the JSON file format 】, as required by projects such as DS-NeRF.

Thank you for your time and dedication to your project.

**Comment by maximeraafat** [comment]
Hi @TaoF02, please excuse me for the late reply, and thank you for your kind words!

For now, I am not planning on adding any further functionalities to the plugin, but what you describe can be achieved directly within Blender. **BlenderNeRF** renders whatever is in the Blender compositor, you can therefore render an additional depth pass, and save the depth images separately in an arbitrary folder (checkout [this pull request](14#issuecomment-1453614119) for details).

If you need both optical images and depth maps to be stored together into a single JSON file, a simple python script should be able to take care of that. Let me know if you run into any issues or if you have any further questions!

Cheers,
Maxime
