### ISSUE TITLE
Is this tool only generate training image directory?

### ISSUE THREAD

**Issue by maluonei** [maximeraafat/BlenderNeRF#25]
I only get a training image diractory, a train json file and a test json file, without a test image directory.

**Comment by maluonei** [comment]
> 

My tool version is 5.0.

**Comment by maximeraafat** [comment]
Hi @maluonei, yes that is how I designed the add-on. Its intended purpose is to extract train and test camera poses such that these views can be rendered in a dedicated NeRF software such as Instant NGP. If you need a respective `test` folder with ground truth images, you can render the images directly with Blender under `Render` > `Render Animation` in the top bar, with the corresponding test camera as active camera. Hope this helps!
