### ISSUE TITLE
Scene is shifting?

### ISSUE THREAD

**Issue by henrypearce4D** [maximeraafat/BlenderNeRF#28]
I'm testing the add-on with Gaussian splatting It seems like the scene is shifting?

Are there any adjustments made on export? can we turn them off?

**Comment by maximeraafat** [comment]
Hi @henrypearce4D,

I didn't get to test **BlenderNeRF** for gaussian splattings yet, but the issue might be related to how the coordinate system is initialised. I noticed though that you closed this issue as completed, so I guess you must have found a solution to your issue.

If you need any further assistance, let me know! And feel free to share your results here (screenshots, what you changed in the add-on code, or any other observations) as a resource for other people that might experience similar difficulties :)

**Comment by henrypearce4D** [comment]
Hi @maximeraafat, everything actually worked as expected, it was user error from our side.

Thanks again for this awesome add-on!

**Comment by maximeraafat** [comment]
Glad to hear everything worked out! :)

**Comment by dafei-qin** [comment]
Hello there,  I encountered similar issues. When only using camera rotations as different views the reconstructed Gaussians are fine, but if I introduce some translation of camera positions, then the optimized Gaussians are inconsistent under different views. 
May I know if you have the same issue and how you deal with this? That would be very helpful!

**Comment by henrypearce4D** [comment]
@dafei-qin 
" are inconsistent under different views."

I think this sounds like a different issue, we can load layers of trained splats and thought they where shifted in the viewport but they weren't, it was the new scene from blender that was shifted

**Comment by dafei-qin** [comment]
Oh, I see. Thanks!
