### ISSUE TITLE
BlenderNeRF Camera not found

### ISSUE THREAD

**Issue by RussRobin** [maximeraafat/BlenderNeRF#29]
Hi, thank you for this meaningful tool.

I tried to render .blender models with BlenderNerf and it works well. However, when I made some modifications on the model (e.g. rotation of a part of it), I encounter errors:
sphere_camera = scene.objects[CAMERA_NAME]
KeyError: 'bpy_prop_collection[key]: key 'BlenderNeRF Camera' not  found'

May you please look into it? Thank you in advance.

**Comment by maximeraafat** [comment]
Thanks for sharing the file! Interesting, it seems like you somehow managed to invert the behaviour of the `BlenderNeRF Camera`. In your situation, the camera is only visible when the corresponding preview button is unselected, which breaks the functionality of the COS method.

But no worries, there is a simple fix. First, enable the  `BlenderNeRF Camera` by **unselecting** the corresponding preview button. Once the camera is visible in your scene, enter the following command in the Blender python console
```python
bpy.data.objects.remove(bpy.data.objects['BlenderNeRF Camera'], do_unlink=True)
```

That should solve the issue, the preview and `PLAY COS` buttons should again behave as expected.
Let me know whether you encounter any further issues!

**Comment by RussRobin** [comment]
Thank you for your help, the problem has been solved for me!

**Comment by maximeraafat** [comment]
Glad I could be of help
