### ISSUE TITLE
How much frame rate can be achieved in blender

### ISSUE THREAD

**Issue by SSground** [maximeraafat/BlenderNeRF#3]
In blender, will the test efficiency be higher than ngp?

**Comment by maximeraafat** [comment]
Hi, let me provide some details to answer this question. "Evaluating" a test image in Blender simply boils down to rendering the frame in question. In contrast, NeRF, or in this case Instant NPG, first trains a model to learn the 3D scene, and is then capable of predicting an image, given a camera.

Depending on your hardware, the rendering parameters and the scene complexity (geometry and materials), Blender can take minutes to hours to render a single frame, especially if using Blender's path-tracer, _Cycles_. When rendering small scenes (simple geometry and materials) with Blender's real-time rasteriser, _Eevee_, Blender usually performs quite fast. But even with _Eevee_, rendering a single frame can still take from seconds to minutes.

Instant NGP on the other side, will take from a few seconds to a very few minutes to train its NeRF model, and is then capable of predicting a test image way faster than almost any renderer. **Therefore, when testing on hundreds of images, Instant NGP will be drastically faster than Blender.**

**Comment by SSground** [comment]
> Hi, let me provide some details to answer this question. "Evaluating" a test image in Blender simply boils down to rendering the frame in question. In contrast, NeRF, or in this case Instant NPG, first trains a model to learn the 3D scene, and is then capable of predicting an image, given a camera.
> 
> Depending on your hardware, the rendering parameters and the scene complexity (geometry and materials), Blender can take minutes to hours to render a single frame, especially if using Blender's path-tracer, _Cycles_. When rendering small scenes (simple geometry and materials) with Blender's real-time rasteriser, _Eevee_, Blender usually performs quite fast. But even with _Eevee_, rendering a single frame can still take from seconds to minutes.
> 
> Instant NGP on the other side, will take from a few seconds to a very few minutes to train its NeRF model, and is then capable of predicting a test image way faster than almost any renderer. **Therefore, when testing on hundreds of images, Instant NGP will be drastically faster than Blender.**

Thanks your answer.

**Comment by NowLoadY** [comment]
!!! sounds great! I will try it
