### ISSUE TITLE
The color of the object in the generated image is different.

### ISSUE THREAD

**Issue by wangjinhoon** [maximeraafat/BlenderNeRF#31]
Hello, I'm new to Blender....i used the object below to execute cos, but the image turns out as shown below. What did I do wrong
![Screenshot from 2024-02-13 15-51-02](https://github.com/maximeraafat/BlenderNeRF/assets/83506637/7a22e6d4-c730-4e67-abb3-1b9019cade6a)

Below is the generated image.
![0001](https://github.com/maximeraafat/BlenderNeRF/assets/83506637/c9aa6eef-5023-4d06-93ca-f8dc343b23f0)
![0002](https://github.com/maximeraafat/BlenderNeRF/assets/83506637/6208c8ed-51ab-44ba-933e-8a28bf494c0d)

Sorry for the many questions.
It seems like the cosine method retrieves images in random order, but can I modify the code to receive sequence data from the starting point

It seems like the SOF method behaves similarly to what I want, right? And does this feature include rendering? Can it be removed

thank your reply!

**Comment by maximeraafat** [comment]
Hi @wangjinhoon, thanks for your question. A rendered object is pink when the textures for the corresponding mesh are missing. If you head to the shader editor, you should be able to change the path to the texture images for the materials in question. If you're struggling with this, just google _Blender missing textures_, you'll find plenty of solutions.

As for your second question, the **COS** method (which stands for Camera on Sphere, not **cosine** 😉) renders images randomly sampled from a sphere. If you'd rather render images in a sequential motion, I'd suggest setting up a camera that follows a curve or is attached (parented) to an empty object. You should find many resources and tutorials to set up such a system online as well.

Note that all three **SOF**, **TTC** and **COS** methods per default render the camera views for the selected cameras and frames (details in the [README](https://github.com/maximeraafat/BlenderNeRF/blob/main/README.md)). You can disable rendering by unticking the `Render Frames` button in the add-on panel.

Hope this helps!

**Comment by wangjinhoon** [comment]
Thank you for always kindly guiding me. The file I attached above generated training images very quickly. However, when I ran COS with other objects containing textures, the speed of generating training images significantly slowed down. Is there a way to speed up this process?

**Comment by wangjinhoon** [comment]
hello @maximeraafat 

 Exactly what I wanted. Thank you for explaining so kindly :)
