### ISSUE TITLE
generating test renderings.

### ISSUE THREAD

**Issue by adam-ce** [maximeraafat/BlenderNeRF#32]
Hi,
I wanted to use this plugin to generate training and test data for our Gaussian splatting implementation.

And it generates training data, but no test data. looking into the code, I saw in cos_operator, that it appears to only write the JSON file. is that possible at all?

thanks, adam

**Comment by maximeraafat** [comment]
Hi @adam-ce, thanks for your question.

Yes you are correct, **BlenderNeRF** was originally designed with the intention of performing inference directly using a NeRF implementation. If you however need testing data, you can directly render it by selecting the camera of interest as active camera in Blender, and render the Blender animation on the desired set of frames (using the `Render` > `Render Animation` button). If the camera you need happens to be the COS camera, just select the `Camera` preview button in the `COS` tab, and then select the created `BlenderNeRF Camera` object as active camera.

Hope this solves your issue!

**Comment by adam-ce** [comment]
thanks for the answer :)
to my understanding (but i might be wrong) that won't create a separate testing set, no? that would just use the same camera views as the training camera(?)

i would need the test views to be rendered with different positions than the training cameras, and referenced in the json file.

**Comment by maximeraafat** [comment]
Yes correct, I should have specified that this will render the same views as for training. You could however disable training by simply unticking the `Train` button in the first **BlenderNeRF** tab, select a different seed for the COS method, and use the previewed `BlenderNeRF` camera as test camera for the COS method (the camera object that you can select at the top of the tab). That should do it :)

**Comment by adam-ce** [comment]
ok. thanks for the help and the effort :)

though at this point the plugin becomes more complicated than our python script. thanks anyways :)

**Comment by maximeraafat** [comment]
My pleasure, and feel free to adapt the plugin to your own needs if it simplifies your pipeline :)
