### ISSUE TITLE
TypeError: empty_fn() missing 1 required positional argument: 'context'

### ISSUE THREAD

**Issue by jiangyijin** [maximeraafat/BlenderNeRF#33]
Hello, I had this problem while running the plugin. How can I solve it?
Traceback (most recent call last):
  File "C:\Users\jUsers\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderNeRF-main\helper.py", line 116, in properties_desgraph_upd
    can_properties_upd(scene)
TypeError: empty_fn() missing 1 required positional argument: 'context'

**Comment by maximeraafat** [comment]
Hi @jiangyijin,

Could you perhaps share a few more details (or directly the `.blend` file) on how you obtained this error message? Thanks!

**Comment by jiangyijin** [comment]
I think it's my blender's problem. I have a good result. Thank you!
