### ISSUE TITLE
glass ceiling on radius parameter

### ISSUE THREAD

**Issue by bastiennes** [maximeraafat/BlenderNeRF#34]
Hello,

Thank you very much for this wonderful tool!
I would like to generate a blender dataset in COS from an object. Unfortunately my object is large, and the radius parameter is limited to 1000m maximum. How can I change the maximum value of this radius?

**Comment by maximeraafat** [comment]
Hi @bastiennes,

Thanks for the message. If you have issues with the radius parameter constraint, you can directly scale the X, Y and Z axes altogether (shortcut hotkey `S` to scale objects in all directions directly) to get the same effect as changing the radius. The scale parameter should not have such limits. Let me know if you encounter further issues!
