### ISSUE TITLE
Request: Support creation of 3DGS datasets

### ISSUE THREAD

**Issue by murcje** [maximeraafat/BlenderNeRF#36]
Hi,

Thank you for your work! Title says it all. I believe it is possible to convert the exports from BlenderNerf to 3DGS but it lacks a pointcloud export atm. And I have had no luck with exporting these manually in a way so that they are compatible with a 3dgs dataset.

Thanks!

**Comment by maximeraafat** [comment]
Hi @murcje,

Thanks for your question! I have currently little time and haven't had many chances to play with 3DGS. As soon as I will though, I will consider adding a feature to export an additional point cloud.

In the meanwhile, you can export a point cloud from a mesh manually by sampling points from the surface in the geometry nodes tab (see the screenshot below: the `points to vertices` node is optional, depending on the export format). If you have multiple meshes, it is probably easier if you join them into a single mesh first. Feel free to play with the distribution density to get the number of points that you want.

<img width="1440" alt="Screenshot 2024-06-07 at 20 46 44" src="https://github.com/maximeraafat/BlenderNeRF/assets/51931580/ec0a4a54-b959-491a-b326-cc7730ef12ed">

Hope this helps!

**Comment by murcje** [comment]
Thank you for you rquick reply! I tried the above, it works, but also does not work fully. It needs rgba values for each point. 

But I can figure this one out myself I think. Would not want to waste your time with helping me use Blender.

Cheers!

**Comment by maximeraafat** [comment]
Hi @murcje,

You can set the colours of each point in the shader editor by creating a very simple material with just an arbitrary diffuse colour. Then apply the material to the points in the geometry nodes setup with the `Set Material` node as last node before the geometry group output.

From my experience with previous point-based reconstruction methods, 3DGS shouldn't care too much about the colour each point has been initialised with, since it will optimise these anyways. The geometry prior however provided with the point initialisation is usually of far greater importance.

Let me know if you encounter any issues setting up the colours!

**Comment by murcje** [comment]
Hi @maximeraafat,

I have a working solution, thanks to your help and ChatGPT!

Here's my workflow, maybe it is helpful in creating an add-on, or just for somebody looking for a way to create 3DGS from Blender scenes:

1. Have your scene setup with multiple cameras, mine is usually a sphere array. 
2. Import your object and light it to taste.
3. Join all objects into one (ctrl-j). 
4. Copy the new object and create a new geometry node for that. 
5. Add a Mesh to Points node in between the in and output. 
6. Run the following script to export a cameras.txt images.txt and points3D.txt along with a render from each camera.

`import bpy
import os
import mathutils

# Output directory
output_dir = "../BLENDERSYNTHDATASET/"
os.makedirs(output_dir, exist_ok=True)
cameras_file = os.path.join(output_dir, "cameras.txt")
images_file = os.path.join(output_dir, "images.txt")
points3D_file = os.path.join(output_dir, "points3D.txt")
images_dir = os.path.join(output_dir, "images")
os.makedirs(images_dir, exist_ok=True)

# Function to get camera intrinsics in COLMAP format
def get_camera_intrinsics(camera):
    scene = bpy.context.scene
    render = scene.render
    K = camera.data.lens
    width = render.resolution_x
    height = render.resolution_y
    fx = K * width / camera.data.sensor_width
    fy = fx  # Assuming square pixels
    cx = width / 2.0
    cy = height / 2.0
    return fx, fy, cx, cy

# Function to convert Blender Z-up to COLMAP Y-up coordinates
def convert_coordinates(cam):
    rotation_mode_bk = cam.rotation_mode
                
    cam.rotation_mode = "QUATERNION"
    cam_rot_orig = mathutils.Quaternion(cam.rotation_quaternion)
    cam_rot = mathutils.Quaternion((
        cam_rot_orig.x,
        cam_rot_orig.w,
        cam_rot_orig.z,
        -cam_rot_orig.y))
    qw = cam_rot.w
    qx = cam_rot.x
    qy = cam_rot.y
    qz = cam_rot.z
    cam.rotation_mode = rotation_mode_bk

    T = mathutils.Vector(cam.location)
    T1 = -(cam_rot.to_matrix() @ T)
    
    tx = T1[0]
    ty = T1[1]
    tz = T1[2]
                
    
    return tx, ty, tz # position.x, position.z, -position.y

# Function to convert Blender rotation to COLMAP format (Hamilton convention)
def convert_rotation(rotation):
    if isinstance(rotation, mathutils.Euler):
        rotation = rotation.to_quaternion()
    # Blender to COLMAP coordinate system transformation
    # Swap and invert z and y to match COLMAP's coordinate system
    quat = rotation
    return [quat.x, quat.w, quat.z, -quat.y]

# Function to export camera intrinsics in COLMAP format
def export_camera_intrinsics(cameras, file_path):
    with open(file_path, 'w') as f:
        f.write("# Camera list with one line of data per camera:\n")
        f.write("#   Camera ID, MODEL, width, height, fx, fy, cx, cy\n")
        f.write("# Number of cameras: 1\n")
        camera = cameras[0]
        fx, fy, cx, cy = get_camera_intrinsics(camera)
        width = bpy.context.scene.render.resolution_x
        height = bpy.context.scene.render.resolution_y
        f.write(f"0 PINHOLE {width} {height} {fx} {fy} {cx} {cy}\n")

# Function to export images metadata in COLMAP format
def export_images_metadata(cameras, file_path, images_dir):
    with open(file_path, 'w') as f:
        f.write("# Image list with two lines of data per image:\n")
        f.write("# IMAGE_ID, QVEC (w, x, y, z), TVEC (x, y, z), CAMERA_ID, NAME\n")
        f.write("# POINTS2D[] as (x, y, POINT3D_ID)\n")
        for cam_id, camera in enumerate(cameras):
            # Get camera pose
            location, rotation, scale = camera.matrix_world.decompose()
            print(cam_id , " " ,  location)
            qvec = convert_rotation(rotation)
            colmap_location = convert_coordinates(camera)
            
            # Image file name
            img_name = f"frame_{cam_id:05d}.png"
            img_path = os.path.join(images_dir, img_name)

            # Render image
            bpy.context.scene.camera = camera
            bpy.context.scene.render.filepath = img_path
            bpy.ops.render.render(write_still=True)

            f.write(f"{cam_id + 1} {qvec[0]} {qvec[1]} {qvec[2]} {qvec[3]} {colmap_location[0]} {colmap_location[1]} {colmap_location[2]} 0 {img_name}\n")
            f.write("\n")

# Function to export 3D points metadata in COLMAP format
def export_points3D_metadata(file_path):
    # Assume we have a point cloud in the selected object
    obj = bpy.context.object
    if obj is None or obj.type != 'MESH':
        print("Error: No mesh object selected.")
        return
    
    vertices = obj.data.vertices
    
    with open(file_path, 'w') as f:
        f.write("# 3D point list with one line of data per point:\n")
        f.write("# POINT3D_ID, X, Y, Z, R, G, B, ERROR, TRACK[] as (IMAGE_ID, POINT2D_IDX)\n")
        
        for idx, vertex in enumerate(vertices):
            x, y, z = obj.matrix_world @ vertex.co  # World coordinates
            r, g, b = 255, 255, 255  # Example color (white)
            error = 1.0  # Example reconstruction error
            track = [(0, idx), (1, idx)]  # Adjust as per your dataset
            track_str = ' '.join([f"{img_id} {point2d_idx}" for img_id, point2d_idx in track])
            f.write(f"{idx} {x} {y} {z} {r} {g} {b} {error} {track_str}\n")

# Get all cameras in the scene
cameras = [obj for obj in bpy.context.scene.objects if obj.type == 'CAMERA']

# Export camera intrinsics to cameras.txt
export_camera_intrinsics(cameras, cameras_file)

# Export images metadata to images.txt
export_images_metadata(cameras, images_file, images_dir)

# Export 3D points metadata to points3D.txt
export_points3D_metadata(points3D_file)

print("Dataset generation complete!")
`

**Comment by maximeraafat** [comment]
Thanks @murcje for sharing! I will consider adding the feature based on your workflow :)

**Comment by maximeraafat** [comment]
Hi @murcje, Gaussian Splatting dataset creation support has been added with the latest **BlenderNeRF** version `5.1.0`. I have implemented it a bit differently than you did, and will soon create a new GitHub release `v6` with further details. I still didn't get to experiment much with 3DGS, so if you get to play with this version and encounter any issues, please let me know :)

**Comment by murcje** [comment]
I tried your add on. It works, but for my workflow I cannot use it. I use splatfacto with Nerfstudio and those datasets differ from the original Inria implementation. I think most people are not using Inria's but rather the MIT or Apache licensed derviatives. 

Perhaps there is some conversion method possible but I am not aware of any atm.

If you ever feel like supporting this, here's some info > 

For Nerfstudio the dataset folder/file structure looks like this:

1. A folder called _images_, with all the rendered images
2. A folder called _sparse_, with in it a folder called _0_ (zero), in that 0 folder there are 3 files:

images.txt, points3D.txt and cameras.txt

images.txt looks like this, For every image there is a line, just showing the first:

# Image list with two lines of data per image:
# IMAGE_ID, QVEC (w, x, y, z), TVEC (x, y, z), CAMERA_ID, NAME
# POINTS2D[] as (x, y, POINT3D_ID)
1 0.049999892711639404 0.7053368091583252 0.7053368091583252 -0.0500001460313797 3.6194765016261954e-06 4.76837158203125e-07 10.000000953674316 0 frame_00000.png

cameras.txt looks like this (just 1 type of camera used so only 1 line):

# Camera list with one line of data per camera:
# Camera ID, MODEL, width, height, fx, fy, cx, cy
# Number of cameras: 1
0 PINHOLE 1920 1080 1333.3333333333333 1333.3333333333333 960.0 540.0

the points3D.txt is below (just 1 line of many):

# 3D point list with one line of data per point:
# POINT3D_ID, X, Y, Z, R, G, B, ERROR, TRACK[] as (IMAGE_ID, POINT2D_IDX)
0 2.3196544647216797 0.8340649604797363 -0.4161362946033478 255 255 255 1.0 0 0 1 0

Thanks!

**Comment by maximeraafat** [comment]
Thanks @murcje for your suggestion, this does indeed sound like a useful feature. But due to my current busy schedule, I do not plan on adding it soon. Feel free to fork the repository and modify it to fit your workflow! :)
