### ISSUE TITLE
Just a question really

### ISSUE THREAD

**Issue by PLAN8VR** [maximeraafat/BlenderNeRF#37]
Hi, thanks for releasing this great tool!

I'm just wondering why the COS cameras have to be random order? Is there a specific reason for this? If they were sequential, it would make more sense when/if checking through them afterwards to identify any clipping or areas that need improvement.

Also, it would be handy to be able to preview the cameras before render (maybe it can do this already but I dont know how)

Anyway, thanks again!

**Comment by maximeraafat** [comment]
Hi @PLAN8VR, thanks for your question!

The **COS** method follows the implementation from the original NeRF code (the original script is linked in [this](https://github.com/bmild/nerf/issues/78) issue). NeRFs and other reconstruction methods essentially do best when all possible view angles are visible in the training data. Randomly placing a camera on a sphere with constant radius while looking at the centre is one of the easiest way to ensure full visibility coverage, both from a methodology and implementation point of view. In other words, the camera in the **COS** method does not really follow any order, but instead gets moved to a new randomly sampled position on the sphere with every new frame.

If you need a more _sequential_ camera motion though, you can achieve that by tracking the camera to an empty placed at the centre of your object of interest. You can then animate the empty object as desired, and use the **SOF** or **TTC** method to extract the corresponding camera data. Let me know if you encounter any difficulties with that!

As for your last question, just select the `BlenderNeRF Camera` (when toggled on in the **COS** preview mode) as active camera. The GIF below demonstrates how to do this. Hope this helps :)

![COS](https://github.com/maximeraafat/BlenderNeRF/assets/51931580/4a7b0ed6-ed27-45a5-9075-f09c6628aa4c)

**Comment by PLAN8VR** [comment]
Hi, thanks for taking the time to answer in such detail!

All the best!
