### ISSUE TITLE
How to adjust the blenderNeRF settings

### ISSUE THREAD

**Issue by lifeiXiao** [maximeraafat/BlenderNeRF#39]
![image](https://github.com/user-attachments/assets/aca23dd9-b1f9-4e08-86cc-e994cf600c8b)
As you see, I get the wrong result when training in NGP, I'm not very sure where i should adjust in BlenderNeRF settings.

Again, i adjust the "scale", and get the result below:
![image](https://github.com/user-attachments/assets/d1ced044-34a9-420f-9529-3efe0df9acd9)
I'm confused. I want to get the center object, but why there has a huge white cube.

**Comment by maximeraafat** [comment]
Hi @lifeiXiao, thanks for your question. NGP creates a NeRF contained within a box, with the scale of the box determined by the `AABB` parameter. The white box colour could be a consequence of rendering with white background. I suggest rendering your Blender scene with a transparent background, which you can do by ticking the `Transparent` box in the `Properties` window under `Render` > `Film`. As for the centring of your scene, this might have to do with the global position of your objects and camera in the Blender scene. If an object is too far from the Blender global origin, the default NGP camera might seem far off your NeRF reconstructed objects. I suggest centring your objects around the origin, and increasing the `AABB` parameter might also be beneficial. Hope this helps!

**Comment by lifeiXiao** [comment]
Cool! @maximeraafat ,I have already solved this problems according to your advice, i think i can do the further research now! Thanks alot again!

**Comment by maximeraafat** [comment]
Glad I could be of help :)
