### ISSUE TITLE
Error when trying to create gaussian points ply

### ISSUE THREAD

**Issue by rpte** [maximeraafat/BlenderNeRF#40]
Hello,

This plugin is really great, but when i'm trying to create a ply file it gives an error

Found out it was the blender version. update from 4.0 to 4.2 and it's working now

**Comment by maximeraafat** [comment]
Hi @rpte, thanks for your message. I see you’ve managed to resolve the issue, though it was indeed a bug unrelated to the Blender version. The problem occurs when no object is active, which can happen if the currently active object is deleted. In that case, Blender loses track of the current context. I’ve addressed this in the [latest commit](https://github.com/maximeraafat/BlenderNeRF/commit/771b1dfd43d654f1ff5c2edf73516f91e7cfdd2d). :)
