### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Erik262** [maximeraafat/BlenderNeRF#5]
I followed your instructions, but for some reason I'm not able to run the addon. This is the error I'm getting, running on latest python version 3.10.8.
Already gave Blender including the addon high rights. Same as for the destination folder.
![image](https://user-images.githubusercontent.com/11977647/202189553-a4b4c5dd-28f6-496f-89c1-58fcace5d309.png)

**Comment by maximeraafat** [comment]
Hi @Erik262, I'm sorry to hear that you are experiencing issues with the code.

I've tried to replicate your issue by running the SOF module with the release v2 version of the addon (I believe you've been using this one, let me know if I'm incorrect), but didn't run into any issues. Could you perhaps let me know the exact steps you've been taking, or at least send me a screenshot of the addon user interface panel with the options you've ticked and chosen?

On a side note, when saying that you gave Blender high rights, do you mean that you gave it the permission to write data on your disk?

**Comment by Erik262** [comment]
Hi @maximeraafat, I fixed that problem by creating the folders by hand. Thats it. The only reason why it was not working. Very strange. I used the version in the release section.

**Comment by maximeraafat** [comment]
Hi @Erik262 , this is a strange behaviour that shouldn't happen, since the addon takes care of creating all the respective folders. Are you sure that you gave all the necessary permissions to Blender?

A good way to check this would be to go to the **Scripting** top panel in Blender, and in the **Python Console** you can enter the following command (be sure to enter any valid existing path for the `path` variable):

```
import os
import json
data = {'testdata': 0}
path = '/Users/<yourname>/Downloads/'
foldername = 'testfolder'
folderpath = os.path.join(path, foldername)
os.makedirs(folderpath, exist_ok=True)
filepath = os.path.join(folderpath, 'test.json')
with open(filepath, 'w') as file:
    json.dump(data, file, indent=4)
```

This code will create a directory called **testfolder** with a **test.json** file, saved under `path`.
Let me know whether this works :)

**Comment by Erik262** [comment]
@maximeraafat 
I'm getting the same error message. I gave Blender full Access to all folders. Creating/Saving a project works in every folder.

![image](https://user-images.githubusercontent.com/11977647/202647767-02ec39ab-9fa4-4245-851a-ff556875d502.png)

**Comment by Erik262** [comment]
Hi @maximeraafat so it is definitely an issue with `os.makedirs(folderpath, exist_ok=True)` If the folder exists, the json file will be created. If not,  the same error appears, as mentioned in my first post. That's very strange, because I run the same code in a seperate python file and it works. But not from the Blender site.

**Comment by maximeraafat** [comment]
Hi @Erik262, in this case the issue does not lie with the addon code, but with your computer's permissions with respect to Blender. Perhaps you could reset the permissions in your settings to grant Blender full access to your computer disk. Another suggestion would be to uninstall Blender and reinstall it from scratch, and grant all the access during the installation process.

I am to be honest unsure on the exact steps you should follow to solve this issue. You might want to verify whether you have administrative rights on your computer. Please feel free to share any progress on this topic in this GitHub issue!
