### ISSUE TITLE
About the trajectory of camera

### ISSUE THREAD

**Issue by kyleleey** [maximeraafat/BlenderNeRF#6]
Hi, thanks for this great add-on

I wonder can the trajectory for this add-on, as "BlenderNeRF sphere", can be set as other shape?

The current default setting is a sphere, and can changed to a circle or a line, but can the trajectory be user-defined? Current sphere traj is suitable for object-level, but seems not a good choice when handling forward-facing scenes.

**Comment by maximeraafat** [comment]
Hi @kyleleey, yes of course, that's what the **Subset of Frames (SOF)** and **Train and Test Cameras (TTC)** methods are for. In the **BlenderNeRF** add-on panel, open the tabs for either the **SOF** or **TTC** method. There you can directly select any existing animated camera, and extract the camera poses for that camera.

You will find more information on how to use the methods [here](https://github.com/maximeraafat/BlenderNeRF#how-to-use-the-methods). I hope this answers your question and if you have more difficulties, feel free to let me know

**Comment by kyleleey** [comment]
Hi, Thanks for the advice. 

However, when I finish setting a curve trajectory and make my camera follows that path, and set that camera in SOF, and when I click "Play SOF", the blender reports: "BlenderNeRF Camera Not Found"

If I change the name of this camera to "BlenderNeRF Camera", this error won't show up and SOF can render frames, however the camera will automatically have offsets to the original set trajectory, and I cannot change this offsets.

Do you know how to fix this problem?

**Comment by maximeraafat** [comment]
Hi @kyleleey,

This is a bug that I have fixed with [this previous commit](https://github.com/maximeraafat/BlenderNeRF/commit/12a24c0a80379e9cb37283f1aadd690bb487559f). You can simply uninstall the add-on, download it again (not the release version v3, as it contains the bug), and install it again. This should fix the issue.

If you encounter any further problems, let me know :)

**Comment by kyleleey** [comment]
Thanks for all the support! Now I can add random camera to run SOF/TTC.
