### ISSUE TITLE
Inside-out sphere option:

### ISSUE THREAD

**Issue by avclubvids** [maximeraafat/BlenderNeRF#8]
The sphere option is great for turntabling an object, but obviously not great for rendering an environment. It would be good to add an option that points the cameras outward to render a room or other environment from somewhere in the center (basically, where you would intend a viewer to see it from).

**Comment by maximeraafat** [comment]
HI @avclubvids,

Thanks for the suggestion, that's actually a great idea. I'll definitely consider adding such an option for the COS method!

**Comment by maximeraafat** [comment]
Hi @avclubvids,

An option for outwards facing cameras for the **Camera on Sphere** method is now available in version v4 of the add-on :)

**Comment by avclubvids** [comment]
@maximeraafat heck yeah!
